### PR TITLE
Added --only-variable and --only-variable-excluding-indels coloring

### PR DESCRIPTION
**Pull request by nikostr**
Hey! I'm working with gene sequences that are very similar to one another. In order to quickly compare these visually, I've found these coloring options to be useful. What do you think about merging these in?

### CODE REVIEW

**Comment by nikostr** [comment]
After fixing `--dotted` as mentioned [here](https://github.com/arvestad/alv/issues/14), this might be superfluous?

**Comment by arvestad** [comment]
This looks like a great improvement. Why would fixing --dotted make this superfluous?

**Comment by nikostr** [comment]
To me, --dotted and these options fill more or less the same purpose, but perhaps they are complementary. They do perform slightly different functions, but I personally think that --dotted is probably what I would use for most of my needs, now that it is working. The only potential harm in adding it would be bloat in code and documentation, I guess :)

**Comment by arvestad** [comment]
I will merge your suggestion. To me, having both color and dots are good alternatives.

**Pull request merged**
